# Generated by Django 4.2.4 on 2023-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='bodyImage',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bodyImage',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
    ]
